// Code generated by gen/version.go; DO NOT EDIT.

package version

// BuildTime is the UTC timestamp from the last "go generate" run.
// Refresh with: go generate ./...
const BuildTime = "2026-10-01T10:27:55Z"
